### PR TITLE
Devcontainer support, including Wokwi simulation, and readme update

### PR DESCRIPTION
**Pull request by SergioGasquez**
Hello! I saw [your tweet](https://twitter.com/jhaand/status/1528334983424880641) a few days ago and wanted to help, so this PR:
- Adds devcontainer support to bootstrap the environment (we can even develop ESP boards in Rust in a  browser app without installing anything :exploding_head: )
  - Devcontainers in VsCode
  - Gitpod
  - GigHub Codespaces
- Wokwi simulation: Since the board was already in Wokwi I was able to use it and simulate Rust code on it, using [`wokwi-server`](https://github.com/MabezDev/wokwi-server). 
  - Wokwi also supports GDB debugging, so I included `launch.json` with the necessary configuration to debug the project from devcontainers
- When using devcontainers, we cant flash with `cargo-espflash` so I added [`web-flash`](https://github.com/bjoernQ/esp-web-flash-server)  to flash real devices from devcontainers!
- Add some task to build, flash, and run Wokwi simualtions from devcontainers
- Updated the code so now it prints a message in the display
  - Please, test it on the real HW as I only tried it on Wokwi :), beaware that you may [need to change this](https://github.com/SergioGasquez/rust4mch/blob/92332c12f69e5bc4f77db27a911bfa8023180183/src/main.rs#L100-L102)
- Updated the readme:
  - Updated installation commands
  - Devcontainers documentation
  - Updated the recommended way to create new projects
    > Both templates repositories will soon have support for devcontainers/wokwi-server/web-flash (I am currently finishing the changes and will make a PR to the esp-rs repos)
- Added default runner in `.cargo/config.toml` to use `cargo-espflash` with `cargo run`
- Added `rust-toolchain.toml` to override the rustup toolchain without having to set `esp` toolchain as default

Thanks for creating this great repo and playing with Rust on the MCH2022 badge! Any feedback or suggestion is more than welcome!

### CODE REVIEW

**Comment by jhaand** [comment]
Hi,
Sorry I missed the notification for the pull request. Cool to make these integrations. I will review them later this evening when I continue working on the code.

**Comment by SergioGasquez** [comment]
No problem! Let me know if you have any questions or suggestions :blush:

**Comment by jhaand** [comment]
Could you rebase and solve the merge conflicts?
It doesn't look like much, but it would help.

**Comment by SergioGasquez** [comment]
> Could you rebase and solve the merge conflicts? It doesn't look like much, but it would help.

Conflicts cleared! Also changed a few details:
- Add the option to use a Dockerhub image for Vs Code and GH Codespaces
- Use release binaries for wokwi-server and web-flash
- Formated Readme
- Finished your `kaluga_hello_world` function to print a message on the display
  - Beware that it might be flipped on your real HW

**Review by jhaand — APPROVED** [review]
This looks very cool. Thank you for all the work.

**Comment by SergioGasquez** [comment]
No problem! Just out of curiosity! Did you have to change anything to make it work in real HW?

**Comment by jhaand** [comment]
No not really, But that is just an ESP32-WROVER with the ili9341 display. 
I just got a real badge today and integrating that with the RP2040 and other stuff will become interesting. To say the least.

**Pull request merged**
